export type CORE_PUBLIC_STRUCTURES =
    'MUSEUM OF THE TREES' | 'GARDENS OF LIFE AND SCIENCE' |
    'WILLIAM\'S BLOCK THEATER' | 'GREEN STADIUM' | 'SOLAR POOL' |
    'THE SPIDER CITY HALL' | 'PHOTOVOLTAIC FARM' | 'SKYRADIO TOWER' |
    'UNIVERSITY OF AGRICULTURE';

// add expansions to union type here
export type PUBLIC_STRUCTURES = CORE_PUBLIC_STRUCTURES;